version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tet_backscreen
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-server1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./main-laravel-project:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: tet_backscreen
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8001:80"

  app-server2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./main-laravel-project:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: tet_backscreen
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8002:80"

  app-server3:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./main-laravel-project:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: tet_backscreen
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8003:80"

volumes:
  db_data:
